import esbuild from 'esbuild';
import process from 'process';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
// Local deploy targets are machine-specific: set OBSIDIAN_PLUGIN_DIRS to a
// path-separator-delimited list, or create deploy.local.json (gitignored).
const localDeploy = fs.existsSync('deploy.local.json')
	? JSON.parse(fs.readFileSync('deploy.local.json', 'utf8')).targetDirs ?? []
	: [];
const vaultPluginDir = (process.env.OBSIDIAN_PLUGIN_DIRS?.split(path.delimiter)[0]) ?? localDeploy[0] ?? '';

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		'node:crypto',
		'crypto',
		'node:fs',
		'fs',
		'node:path',
		'path'
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

const targetDirs = process.env.OBSIDIAN_PLUGIN_DIRS
	? process.env.OBSIDIAN_PLUGIN_DIRS.split(path.delimiter).filter(Boolean)
	: localDeploy;

if (prod) {
	await context.rebuild();
	for (const dir of targetDirs) {
		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}
		fs.copyFileSync('main.js', path.join(dir, 'main.js'));
		fs.copyFileSync('manifest.json', path.join(dir, 'manifest.json'));
		if (fs.existsSync('styles.css')) {
			fs.copyFileSync('styles.css', path.join(dir, 'styles.css'));
		}
		console.log('Successfully bundled and copied plugin to:', dir);
	}
	process.exit(0);
} else {
	await context.watch();
}
