/**
 * RFC 6962 Merkle tree.
 *
 * The load-bearing tests are the golden vectors: roots generated by the vault's
 * `_merkle.py` and asserted here. Two provenance implementations that disagree
 * on the root would be worse than one honest flat digest, so parity is the
 * requirement and this is how it is held.
 *
 * Regenerate with:
 *   python -c "import _merkle, json; ..."   (see the commit that added this file)
 */

const crypto = require('crypto');
const golden = require('./merkle.golden.json');
const {
  MERKLE_ALGORITHM, leafHash, nodeHash, merkleRoot,
  inclusionProof, verifyProof, buildLevels
} = require('../dist/index.js');

describe('parity with the Python implementation', () => {
  for (const [name, vec] of Object.entries(golden)) {
    test(`root matches _merkle.py for "${name}"`, () => {
      expect(merkleRoot(vec.artifacts)).toBe(vec.root);
    });
  }

  test('the empty tree is sha256 of nothing, as RFC 6962 specifies', () => {
    expect(merkleRoot({})).toBe(crypto.createHash('sha256').update(Buffer.alloc(0)).digest('hex'));
  });

  for (const [name, vec] of Object.entries(golden)) {
    if (!vec.proof) continue;
    test(`inclusion proof matches _merkle.py for "${name}"`, () => {
      const p = inclusionProof(vec.artifacts, vec.proof.artifact);
      expect(p.leaf_sha256).toBe(vec.proof.leaf_sha256);
      expect(p.merkle_root).toBe(vec.proof.merkle_root);
      expect(p.proof).toEqual(vec.proof.proof);
    });
  }
});

describe('domain separation', () => {
  test('a leaf and a node over the same bytes hash differently', () => {
    // Without the 0x00/0x01 prefixes an internal node could be presented as a
    // leaf - a second-preimage attack on the tree shape.
    const a = Buffer.alloc(32, 1);
    const b = Buffer.alloc(32, 2);
    expect(leafHash(Buffer.concat([a, b])).toString('hex'))
      .not.toBe(nodeHash(a, b).toString('hex'));
  });
});

describe('odd nodes are promoted, not duplicated', () => {
  test('three leaves do not collide with four where the last is repeated', () => {
    // Duplicating the final leaf lets two distinct trees share a root -
    // CVE-2012-2459 in Bitcoin.
    const three = { a: { sha256: '11'.repeat(32) }, b: { sha256: '22'.repeat(32) }, c: { sha256: '33'.repeat(32) } };
    const dupLevels = buildLevels([
      leafHash(Buffer.from('11'.repeat(32) + '  a', 'utf8')),
      leafHash(Buffer.from('22'.repeat(32) + '  b', 'utf8')),
      leafHash(Buffer.from('33'.repeat(32) + '  c', 'utf8')),
      leafHash(Buffer.from('33'.repeat(32) + '  c', 'utf8'))
    ]);
    const dupRoot = dupLevels[dupLevels.length - 1][0].toString('hex');
    expect(merkleRoot(three)).not.toBe(dupRoot);
  });
});

describe('inclusion proofs', () => {
  const mk = (n) => Object.fromEntries(
    Array.from({ length: n }, (_, i) => [`f${String(i).padStart(3, '0')}.md`,
      { sha256: crypto.createHash('sha256').update(String(i)).digest('hex') }])
  );

  test.each([1, 2, 3, 5, 8, 17, 64])('every leaf verifies in a tree of %i', (n) => {
    const artifacts = mk(n);
    const root = merkleRoot(artifacts);
    for (const path of Object.keys(artifacts)) {
      const proof = inclusionProof(artifacts, path);
      expect(proof.merkle_root).toBe(root);
      expect(verifyProof(proof)).toBe(true);
    }
  });

  test('proof length is logarithmic, not linear', () => {
    const proof = inclusionProof(mk(64), 'f000.md');
    expect(proof.tree_size).toBe(64);
    expect(proof.proof.length).toBe(6);      // log2(64)
  });

  test('a tampered sibling breaks the proof', () => {
    const artifacts = mk(8);
    const proof = inclusionProof(artifacts, 'f003.md');
    proof.proof[0].hash = 'ff'.repeat(32);
    expect(verifyProof(proof)).toBe(false);
  });

  test('a flipped side breaks the proof', () => {
    // Order matters: nodeHash(l, r) is not nodeHash(r, l).
    const proof = inclusionProof(mk(8), 'f003.md');
    proof.proof[0].side = proof.proof[0].side === 'left' ? 'right' : 'left';
    expect(verifyProof(proof)).toBe(false);
  });

  test('a proof cannot be reused for a different leaf', () => {
    const artifacts = mk(8);
    const a = inclusionProof(artifacts, 'f001.md');
    const b = inclusionProof(artifacts, 'f006.md');
    expect(verifyProof({ ...a, leaf_sha256: b.leaf_sha256 })).toBe(false);
  });

  test('an unknown artifact yields no proof', () => {
    expect(inclusionProof(mk(4), 'nope.md')).toBeNull();
  });

  test('the proof declares its algorithm', () => {
    expect(inclusionProof(mk(4), 'f000.md').algorithm).toBe(MERKLE_ALGORITHM);
  });

  test('verifyProof enforces expectedRoot when supplied', () => {
    const artifacts = mk(8);
    const root = merkleRoot(artifacts);
    const proof = inclusionProof(artifacts, 'f003.md');
    expect(verifyProof(proof, root)).toBe(true);
    expect(verifyProof(proof, '00'.repeat(32))).toBe(false);

    // If proof.merkle_root is tampered to match expectedRoot, the computed path fails
    const forgedProof = { ...proof, merkle_root: '11'.repeat(32) };
    expect(verifyProof(forgedProof, '11'.repeat(32))).toBe(false);
  });
});

describe('root sensitivity', () => {
  test('changing one artifact hash moves the root', () => {
    const a = { 'x.md': { sha256: 'aa'.repeat(32) } };
    const b = { 'x.md': { sha256: 'ab'.repeat(32) } };
    expect(merkleRoot(a)).not.toBe(merkleRoot(b));
  });

  test('renaming an artifact moves the root, because the path is in the leaf', () => {
    const a = { 'x.md': { sha256: 'aa'.repeat(32) } };
    const b = { 'y.md': { sha256: 'aa'.repeat(32) } };
    expect(merkleRoot(a)).not.toBe(merkleRoot(b));
  });

  test('insertion order does not matter, because leaves are sorted', () => {
    const a = { 'b.md': { sha256: '22'.repeat(32) }, 'a.md': { sha256: '11'.repeat(32) } };
    const b = { 'a.md': { sha256: '11'.repeat(32) }, 'b.md': { sha256: '22'.repeat(32) } };
    expect(merkleRoot(a)).toBe(merkleRoot(b));
  });
});

describe('scanAndAudit produces a verifiable tree', () => {
  const fs = require('fs'), os = require('os'), path = require('path');
  const { ProvenanceVault } = require('../dist/index.js');
  let tmp;
  beforeEach(() => {
    tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'tree-'));
    fs.mkdirSync(path.join(tmp, 'sub'), { recursive: true });
    fs.writeFileSync(path.join(tmp, 'a.md'), 'alpha');
    fs.writeFileSync(path.join(tmp, 'sub', 'b.md'), 'beta');
    fs.writeFileSync(path.join(tmp, 'sub', 'c.md'), 'gamma');
  });
  afterEach(() => fs.rmSync(tmp, { recursive: true, force: true }));

  test('reports the RFC 6962 algorithm, not a flat digest', async () => {
    const r = await new ProvenanceVault(tmp).scanAndAudit();
    expect(r.algorithm).toBe(MERKLE_ALGORITHM);
  });

  test('artifact keys are POSIX paths, so roots agree across platforms', async () => {
    const { artifacts } = await new ProvenanceVault(tmp).scanAndAudit();
    expect(Object.keys(artifacts).sort()).toEqual(['a.md', 'sub/b.md', 'sub/c.md']);
  });

  test('every scanned file can be proved against the published root', async () => {
    const vault = new ProvenanceVault(tmp);
    const { merkleRoot: root, artifacts } = await vault.scanAndAudit();
    for (const rel of Object.keys(artifacts)) {
      const proof = await vault.proveInclusion(rel);
      expect(proof.merkle_root).toBe(root);
      expect(verifyProof(proof)).toBe(true);
    }
  });

  test('a file not in the vault cannot be proved', async () => {
    expect(await new ProvenanceVault(tmp).proveInclusion('ghost.md')).toBeNull();
  });
});
