import * as crypto from 'crypto';

/**
 * RFC 6962 Merkle tree over vault artifacts, with inclusion proofs.
 *
 * WHY THIS REPLACES scanAndAudit's ROOT
 * -------------------------------------
 * `ProvenanceVault.scanAndAudit` computed its "merkleRoot" as a single SHA-256
 * over every hash concatenated together. That is a manifest checksum. It detects
 * that something changed and nothing else - in particular it cannot produce an
 * inclusion proof, which is the only reason to use a tree in the first place.
 *
 * With a tree, a third party can verify ONE document against a published root
 * without downloading the whole registry: log2(n) hashes, about 9 for a few
 * hundred artifacts. With a linear digest they would need every artifact hash in
 * the vault to check a single file.
 *
 * DOMAIN SEPARATION
 * -----------------
 * Leaves are hashed with a 0x00 prefix and internal nodes with 0x01. Without it
 * an internal node can be presented as a leaf - a second-preimage attack on the
 * tree shape.
 *
 * Odd nodes are PROMOTED, never duplicated. Duplicating the last leaf lets two
 * distinct trees share a root, which is the Bitcoin CVE-2012-2459 class of bug.
 *
 * PARITY WITH THE PYTHON IMPLEMENTATION
 * -------------------------------------
 * This is a deliberate port of the vault's `_merkle.py` and must agree with it
 * byte for byte - two disagreeing provenance implementations would be worse than
 * one honest flat digest. Leaf ordering, leaf encoding (note the TWO spaces
 * between hash and path) and the empty-tree value are all fixed by that
 * requirement, and `merkle.test.ts` checks against roots generated by the Python.
 */

export const MERKLE_ALGORITHM = 'merkle-sha256-rfc6962';

const LEAF_PREFIX = Buffer.from([0x00]);
const NODE_PREFIX = Buffer.from([0x01]);

const sha256 = (b: Buffer): Buffer => crypto.createHash('sha256').update(b).digest();

export const leafHash = (data: Buffer): Buffer =>
  sha256(Buffer.concat([LEAF_PREFIX, data]));

export const nodeHash = (left: Buffer, right: Buffer): Buffer =>
  sha256(Buffer.concat([NODE_PREFIX, left, right]));

export interface ArtifactEntry { sha256: string; }
export type ArtifactMap = Record<string, ArtifactEntry>;

export interface ProofStep { side: 'left' | 'right'; hash: string; }

export interface InclusionProof {
  algorithm: string;
  artifact: string;
  leaf_sha256: string;
  leaf_index: number;
  tree_size: number;
  proof: ProofStep[];
  merkle_root: string;
}

/**
 * Deterministic leaf order: sorted by path. Walk order is not stable across
 * filesystems; sorting is.
 */
export function leavesFromRegistry(artifacts: ArtifactMap): Array<[string, Buffer]> {
  return Object.keys(artifacts).sort().map(p =>
    [p, leafHash(Buffer.from(`${artifacts[p].sha256}  ${p}`, 'utf8'))] as [string, Buffer]
  );
}

/** Every level, leaves first, root last. */
export function buildLevels(leaves: Buffer[]): Buffer[][] {
  if (leaves.length === 0) return [[sha256(Buffer.alloc(0))]];
  const levels: Buffer[][] = [leaves];
  while (levels[levels.length - 1].length > 1) {
    const cur = levels[levels.length - 1];
    const next: Buffer[] = [];
    for (let i = 0; i + 1 < cur.length; i += 2) next.push(nodeHash(cur[i], cur[i + 1]));
    if (cur.length % 2) next.push(cur[cur.length - 1]);   // promote, never duplicate
    levels.push(next);
  }
  return levels;
}

export function merkleRoot(artifacts: ArtifactMap): string {
  const leaves = leavesFromRegistry(artifacts).map(([, h]) => h);
  const levels = buildLevels(leaves);
  return levels[levels.length - 1][0].toString('hex');
}

/** The sibling hashes needed to rebuild the root from one leaf. */
export function inclusionProof(artifacts: ArtifactMap, target: string): InclusionProof | null {
  const entries = leavesFromRegistry(artifacts);
  const idx = entries.findIndex(([p]) => p === target);
  if (idx === -1) return null;

  const levels = buildLevels(entries.map(([, h]) => h));
  const proof: ProofStep[] = [];
  let i = idx;

  for (const level of levels.slice(0, -1)) {
    const sibling = i ^ 1;
    if (sibling < level.length) {
      proof.push({
        side: sibling > i ? 'right' : 'left',
        hash: level[sibling].toString('hex')
      });
    }
    // A promoted node has no sibling at this level; the index still halves.
    i = Math.floor(i / 2);
  }

  return {
    algorithm: MERKLE_ALGORITHM,
    artifact: target,
    leaf_sha256: entries[idx][1].toString('hex'),
    leaf_index: idx,
    tree_size: entries.length,
    proof,
    merkle_root: levels[levels.length - 1][0].toString('hex')
  };
}

/** Recompute the root from a leaf plus its audit path. Needs no other artifact. */
export function verifyProof(proof: InclusionProof): boolean {
  // Annotated: Buffer.from(hex) infers a narrower Buffer than the crypto
  // digest returns, so the reassignment below will not type-check without it.
  let h: ReturnType<typeof leafHash> = Buffer.from(proof.leaf_sha256, 'hex');
  for (const step of proof.proof) {
    const sib = Buffer.from(step.hash, 'hex');
    h = step.side === 'left' ? nodeHash(sib, h) : nodeHash(h, sib);
  }
  return h.toString('hex') === proof.merkle_root;
}
